EmployeeLeavemanagement/urls.py
"""EmployeeLeavemanagement URL Configuration
"""

from django.contrib import admin
from django.urls import path,include
from Leave import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='home'),
    # path('apply/', views.createLeave, name='apply'),

]

Leave/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date,datetime
# Create your models here.

LEAVE_STATUS_CHOICES = (
    ('pending', 'Pending'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected'),
)

class LeaveType(models.Model):
	name=models.CharField(max_length=500)
	desc=models.TextField(blank=True, null=True)

	def __str__(self):
		return self.name

def differ_days(date1, date2):

    a = date1
    b = date2
    return (a-b).days


class Leave(models.Model):
	date_format = "%m/%d/%Y"

	user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)
	leave_type = models.ForeignKey(LeaveType,on_delete=models.CASCADE)
	start_date = models.DateField(null=False)
	end_date = models.DateField(null=True)

	days=models.IntegerField(default=differ_days((date(2016,10,12)), date(2015,12,10)))

	status= models.CharField(max_length=120, default='pending',choices=LEAVE_STATUS_CHOICES)

	def __str__(self):
	    return str(self.leave_type)

Leave/forms.py
from django import forms

from django.contrib.auth.models import User
from .models import Leave
from django.contrib.admin.widgets import AdminDateWidget


class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "password", "first_name", "last_name", "email")

class LeaveForm(forms.ModelForm):

	# start_date = forms.DateField(widget=forms.DateInput(format = '%m/%d/%Y'))
	# end_date = forms.DateField(widget=forms.DateInput(format = '%d/%m/%Y'))


	class Meta:
	    model = Leave
	    fields = ("leave_type", "start_date", "end_date")
	    widgets = {
		    'end_date': forms.DateTimeInput(attrs={'class': 'datepicker'}),
		    'start_date': forms.DateTimeInput(attrs={'class': 'datepicker'})

		}

Leave/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView,UpdateView
from .models import LeaveType,Leave
from .forms import LeaveForm
from django.core.mail import EmailMessage


@login_required(login_url='/accounts/login/')
def index(request):
	if request.method == 'POST':
	    form = LeaveForm(request.POST)
	    if form.is_valid():
	    	leave = form.save(commit = False)
	    	leave.user = request.user

	    	leave.save()
	    	sendMail(request)
	    	return HttpResponseRedirect('/')

	else:
	    form = LeaveForm()
	return render(request, 'index.html', {'form': form})



def sendMail(request):
	username = request.user
	email = EmailMessage('Leave Application', 'New Leave Application From ' +str(username), to=['brianoroni6@gmail.com'])
	email.send()
	return HttpResponseRedirect('/')

templates/base.html
{% load staticfiles %}
{% load bootstrap_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>

  <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

  <script
  src="https://code.jquery.com/ui/1.10.3/jquery-ui.min.js"
  integrity="sha256-lnH4vnCtlKU2LmD0ZW1dU7ohTTKrcKP50WA9fa350cE="
  crossorigin="anonymous"></script>

  <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />


  
  {% block script %}{% endblock %}
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-2 col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2 content">
          {% block page %}

          {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/base_signup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

</head>
<body class="bg-gray">

    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <br/>
          <br/>
          <br/>
          <div class="panel panel-body">
            <div class="panel-body">
              <h3 class="text-center text-uppercase"><b>{% block heading %}{% endblock %}</b></h3>
              <br/>
              {% block content %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load bootstrap_tags %}

{% block title %} Leave Management {% endblock %}



{% block page %}
    <div class="col-lg-offset-0.1 col-lg-10">
        <div class="panel">
            <div class="panel-heading bg-gray">
                <h2 class="panel-title text-center text-white">
                    Apply For Leave 
                </h2>

                  <button class="btn">
                <a href="{% url 'logout' %}">Logout</a>
            </button>

            </div>
            <div class="panel-body">


               <form method="post" novalidate>
                  {% csrf_token %}

                  {{ form|as_bootstrap }}

                  {{ form.days.as_hidden }}
                    <button type="submit" onclick="myfunc()" class="btn btn-primary">
                      Submit
                    </button>

                    </form>
                             
          

            </div>
        </div>
    </div>

    <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "2018:2050",
      format: '%m/%d/%Y',

      // You can put more options here.

    });
  });
  </script>
<script type="text/javascript">
  function myfunc(){

    var start = $('#id_start_date').val();
    var end = $('#id_end_date').val();
    var diff = new Date(end - start);
    var days = diff/1000/60/60/24;
    $("id_days").val(days);

}
</script>
{% endblock %}